### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by rstropek** [rstropek-teaching/converter-quiz-4bhif-micky8186#1]
Congrats! All tests are green, you extra point is secured. I have added some tips as comments to your code.

Could you please send me your real name either per email (rainer@timecockpit.com) or by answering to this issue?

Greetings,
Rainer Stropek.

**Comment by ghost** [comment]
Yes of course!
My name is Markus Dalpiaz.

**Comment by rstropek** [comment]
Thank you.
